[programs.localnet]
harmonia="HARm9wjX7iJ1eqQCckXdd1imRFXE6PsVChVdV4PbfLc"
candy_machine = "CANHaiDd6HPK3ykgunmXFNZMrZ4KbZgEidY5US2L8CTw"

[programs.devnet]
harmonia="HARm9wjX7iJ1eqQCckXdd1imRFXE6PsVChVdV4PbfLc"
candy_machine = "CANHaiDd6HPK3ykgunmXFNZMrZ4KbZgEidY5US2L8CTw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/nuhutuh25/.config/solana/devnet.json"

[scripts]
test = "mocha -t 1000000 tests/"